// Generated by make gen-fields. Do not edit.
export interface ItemFields {
  id: string;
  key: string;
  title: string;
  body: string | null;
  version: number;
  change_seq: number;
  config_version: number;
  rank: string;
  points: number | null;
  start_date: string | null;
  due_date: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  status: { key: string; name: string; category: string };
  assignee: { id: string; display_name: string } | null;
  type: { key: string; name: string; level: number };
  parent: { key: string } | null;
  project: { key_prefix: string; name: string };
  fields: Record<string, unknown>;
  rollup: { descendant_count: number; done_count: number; points_total: number; points_done: number; earliest_start: string | null; latest_due: string | null };
}
export type FieldName =
  | "assignee"
  | "assignee.display_name"
  | "assignee.id"
  | "body"
  | "change_seq"
  | "config_version"
  | "created_at"
  | "deleted_at"
  | "due_date"
  | "fields"
  | "id"
  | "key"
  | "parent"
  | "parent.key"
  | "points"
  | "project"
  | "project.key_prefix"
  | "project.name"
  | "rank"
  | "rollup"
  | "rollup.descendant_count"
  | "rollup.done_count"
  | "rollup.earliest_start"
  | "rollup.latest_due"
  | "rollup.points_done"
  | "rollup.points_total"
  | "start_date"
  | "status"
  | "status.category"
  | "status.key"
  | "status.name"
  | "title"
  | "type"
  | "type.key"
  | "type.level"
  | "type.name"
  | "updated_at"
  | "version"
  | `fields.${string}`;
