import { readFileSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const source = readFileSync('src/routes/table.ts', 'utf8');
export function generate(source, reserved, handlers) {
  const rows = [
    ...source.matchAll(
      /\{ id: '([a-z]+)', path: '([^']+)', eager: (true|false), handler: '(\w+)' \}/g,
    ),
  ];
  assert(rows.length > 0, 'No routes');
  assert.equal(
    rows.filter((r) => r[3] === 'true').length,
    1,
    'Exactly one eager route',
  );
  for (const [, , path, , handler] of rows) {
    const root = path.split('/')[1];
    if (root && !root.startsWith(':'))
      assert(
        reserved.includes(`"${root.toUpperCase()}"`),
        `Unreserved root ${root}`,
      );
    assert(
      handlers.includes(`func (s *Server) ${handler}(`),
      `Missing handler ${handler}`,
    );
  }
  return (
    '// Code generated by make gen-routes; DO NOT EDIT.\npackage api\n\nimport "net/http"\n\nfunc (s *Server) documentRoutes() map[string]http.HandlerFunc {\n\treturn map[string]http.HandlerFunc{\n' +
    rows.map((r) => `\t\t"${r[2]}": s.${r[4]},\n`).join('') +
    '\t}\n}\n'
  );
}
const reserved = readFileSync('../internal/api/reserved.go', 'utf8');
const handlers = readFileSync('../internal/api/documents.go', 'utf8');
const output = generate(source, reserved, handlers);
if (process.argv.includes('--prove')) {
  assert.throws(() =>
    generate(source.replace("'/login'", "'/unreserved'"), reserved, handlers),
  );
  assert.throws(() =>
    generate(
      source.replace("'bootstrapList'", "'missing'"),
      reserved,
      handlers,
    ),
  );
  assert.throws(() =>
    generate(source.replace('eager: false', 'eager: true'), reserved, handlers),
  );
  assert.throws(() => assert.equal(output + '// drift', output));
  console.log(
    'route proofs: unreserved prefix, missing handler, eager count and generated drift rejected',
  );
} else if (process.argv.includes('--check')) {
  assert.equal(
    readFileSync('../internal/api/routes_generated.go', 'utf8'),
    output,
    'Run make gen-routes',
  );
  console.log('gate-routes: OK');
} else writeFileSync('../internal/api/routes_generated.go', output);
