// Code generated by make gen-routes; DO NOT EDIT.
package api

import "net/http"

func (s *Server) documentRoutes() map[string]http.HandlerFunc {
	return map[string]http.HandlerFunc{
		"/": s.bootstrapList,
		"/login": s.bootstrapLogin,
		"/privacy": s.bootstrapPrivacy,
		"/copyright": s.bootstrapCopyright,
		"/third-party": s.bootstrapThirdParty,
		"/:key": s.bootstrapItem,
	}
}
